### ISSUE TITLE
execution Command error

### ISSUE THREAD

**Issue by holyday23** [TnYtCoder/InstaPilot#1]
The command does not run and an error appears. I think I need to fix it with a new command.

**Comment by TnYtCoder** [comment]
Can you explain it properly ?

**Comment by holyday23** [comment]
I started with Python 3 and tried copying the command, but I got a weird error code and I can't

I'm out now, so I'll give you more details when I get home. Thank you for your immediate feedback

**Comment by holyday23** [comment]
git clone https://github.com/TnYtCoder/InstaPilot
I only enter here and it says SyntaxError: invalid syntax.

cd InstaPilot
File"<stdin>" line 1

appears. What should I do?

**Comment by TnYtCoder** [comment]
Share me screenshot

**Comment by holyday23** [comment]
![123](https://github.com/TnYtCoder/InstaPilot/assets/148984880/1bfd8905-4819-4f26-a865-f33b9306aa02)

**Comment by TnYtCoder** [comment]
Broo... You need terminal or **download zip file**

![IMG_20231026_182221](https://github.com/TnYtCoder/InstaPilot/assets/115485810/a4514b77-2e8f-4a14-b147-b2ab1bc1cf3b)

You should check out some videos related to git on YouTube !

**Comment by holyday23** [comment]
omg...I was doing it wrong. Thank you for the kind explanation!
