### ISSUE TITLE
Please explain what the problem is.

### ISSUE THREAD

**Issue by holyday23** [TnYtCoder/InstaPilot#2]
![zfzfewc](https://github.com/TnYtCoder/InstaPilot/assets/148984880/8ae72955-bbdc-4cdc-8651-564f519ca9ba)

I don't think I can install it like the picture above. Please explain how to do it.

**Comment by TnYtCoder** [comment]
``It seems like you're running it in Windows CMD. I recommend running it in Kali Linux.``

It's possible that Instagrapi is not installed. Please try the following command:

```
pip3 install instagrapi
```

``If you encounter any errors, you can watch some tutorials on YouTube to learn how to install pip``
